
if (!isdirectory(expand("$HOME/.cache/vim/repos/github.com/Shougo/dein.vim")))
  call system(expand("mkdir -p $HOME/.cache/vim/repos/github.com"))
  call system(expand("git clone https://github.com/Shougo/dein.vim $HOME/.cache/vim/repos/github.com/Shougo/dein.vim"))
endif

set runtimepath+=~/.cache/vim/repos/github.com/Shougo/dein.vim/
call dein#begin(expand('~/.cache/vim'))
call dein#add('Shougo/dein.vim')

call dein#load_toml('~/.vim/rc/dein.toml', {'lazy': 0})
call dein#load_toml('~/.vim/rc/deinlazy.toml', {'lazy' : 1})


if dein#check_install()
  call dein#install()
  let pluginsExist=1
endif

call dein#end()
call dein#save_state()
