[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'ddc.vim'
depends = ['denops.vim']

[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
depends = ['denops.vim']
hook_source = '''
call ddc#custom#patch_global('ui', 'native')
call ddc#custom#patch_global('sources', ['around'])
call ddc#custom#patch_global('sourceOptions', {
			\ '_':{
			\ 'matchers': ['matcher_head'],
			\ 'sorters': ['sorter_rank']},
			\})
call ddc#enable()
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'


[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'
on_source = 'ddc.vim'


[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'tpope/vim-sorround'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'mattn/vim-maketable'
