export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"


alias h=history
export HISTFILE=${HOME}/.zsh_history
export HISTSIZE=1000
export SAVEHIST=100000

setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS

plugins=(git
	zsh-autosuggestions 
	zsh-vi-mode
	)

source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/home/ma/.bin/anaconda3/bin:$PATH"
export PATH="/home/ma/.bin/charm/bin:$PATH"


source zsh-autocomplete/zsh-autocomplete.plugin.zsh
